name: Push Image To Docker Hub
on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: actions/checkout@v1
      
      - name: docker build && docker push
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          PASSWORD: ${{ secrets.DOCKER_TOKEN }}
          BUILD_PATH: .devcontainer
          IMAGENAME: "popunbom/docker-for-ctf"
          LATEST: true
